name: Build EpiDoc Stylesheets Release

on:
  push:
    tags:
      - 'v*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup env"
        run: |
          export RELEASE_VERSION=${GITHUB_REF#refs/*/}
          echo "RELEASE_VERSION=$RELEASE_VERSION" >> $GITHUB_ENV
      - name: "Checkout latest branch"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: latest
          path: latest
      - name: "Update latest branch"
        run: |
          cd latest
          git merge --ff-only origin/master
          git push origin latest
          cd ..
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "EpiDoc Stylesheets Release ${{ env.RELEASE_VERSION }}"
          tag_name: ${{ env.RELEASE_VERSION }}